- hosts: webservers
  become: true
  become_user: root
  tasks:
  - name: start docker
    service: name=docker state=started
  - name: get the dockerfile from githib
    git: repo=https://github.com/rathiyakaran/AnsibleDockerdemo.git dest=/tmp/gitrepo
  - name: build dockerfile
    command: chdir=/tmp/gitrepo docker build -t myimage .
  - name: run the dockerfile
    command: docker run -d -P myimage
